<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33512" started-at="2023-04-14T17:01:18 CDT" finished-at="2023-04-14T17:01:51 CDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33512" started-at="2023-04-14T17:01:18 CDT" finished-at="2023-04-14T17:01:51 CDT">
      <class name="com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login">
        <test-method status="FAIL" signature="verifyLoginWithValidcredentials()[pri:1, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="verifyLoginWithValidcredentials" duration-ms="362" started-at="2023-04-14T17:01:18 CDT" data-provider="validCredenialsSupplier" finished-at="2023-04-14T17:01:18 CDT">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login.verifyLoginWithValidcredentials()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: verifyLoginWithValidcredentials([])
Arguments: [(java.lang.String) wissamhaddou95@gmail.com,(java.lang.String) Wissam1995]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login.verifyLoginWithValidcredentials()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: verifyLoginWithValidcredentials([])
Arguments: [(java.lang.String) wissamhaddou95@gmail.com,(java.lang.String) Wissam1995]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithValidcredentials -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="setup" is-config="true" duration-ms="9424" started-at="2023-04-14T17:01:18 CDT" finished-at="2023-04-14T17:01:27 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLoginWithInvalidcredentials()[pri:2, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="verifyLoginWithInvalidcredentials" duration-ms="254" started-at="2023-04-14T17:01:27 CDT" finished-at="2023-04-14T17:01:28 CDT">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
at com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login.verifyLoginWithInvalidcredentials(Login.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidcredentials -->
        <test-method status="PASS" signature="teadown()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="teadown" is-config="true" duration-ms="684" started-at="2023-04-14T17:01:28 CDT" finished-at="2023-04-14T17:01:28 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="setup" is-config="true" duration-ms="6915" started-at="2023-04-14T17:01:28 CDT" finished-at="2023-04-14T17:01:35 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLoginwithinvalidemailandvalidpassword()[pri:3, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="verifyLoginwithinvalidemailandvalidpassword" duration-ms="870" started-at="2023-04-14T17:01:35 CDT" finished-at="2023-04-14T17:01:36 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected warning message is displayed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected warning message is displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login.verifyLoginwithinvalidemailandvalidpassword(Login.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginwithinvalidemailandvalidpassword -->
        <test-method status="PASS" signature="teadown()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="teadown" is-config="true" duration-ms="747" started-at="2023-04-14T17:01:36 CDT" finished-at="2023-04-14T17:01:37 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="setup" is-config="true" duration-ms="6220" started-at="2023-04-14T17:01:37 CDT" finished-at="2023-04-14T17:01:43 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyLoginwithvalidemailandinvalidpassword()[pri:4, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="verifyLoginwithvalidemailandinvalidpassword" duration-ms="202" started-at="2023-04-14T17:01:43 CDT" finished-at="2023-04-14T17:01:43 CDT">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
at com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login.verifyLoginwithvalidemailandinvalidpassword(Login.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginwithvalidemailandinvalidpassword -->
        <test-method status="PASS" signature="teadown()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="teadown" is-config="true" duration-ms="668" started-at="2023-04-14T17:01:43 CDT" finished-at="2023-04-14T17:01:44 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="setup" is-config="true" duration-ms="6062" started-at="2023-04-14T17:01:44 CDT" finished-at="2023-04-14T17:01:50 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyloginwithoutprividingcredentials()[pri:5, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="verifyloginwithoutprividingcredentials" duration-ms="405" started-at="2023-04-14T17:01:50 CDT" finished-at="2023-04-14T17:01:50 CDT">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at java.lang.String.contains(String.java:2133)
at com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login.verifyloginwithoutprividingcredentials(Login.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginwithoutprividingcredentials -->
        <test-method status="PASS" signature="teadown()[pri:0, instance:com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login@77846d2c]" name="teadown" is-config="true" duration-ms="661" started-at="2023-04-14T17:01:50 CDT" finished-at="2023-04-14T17:01:51 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadown -->
      </class> <!-- com.tutorialsninja.framwork.tutorialsninjahybridframwork.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
